### ISSUE TITLE
Port runtime observation and solidity-data decoding features

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/edr#246]
This is a tracking issue created as a result of #242. We analyzed this scope with @fvictorio, split it into smaller submodule, and uncover their dependencies and came up with an execution plan.

## Features withing scope

* Generating solidity stack traces
* Inferring common error cases based on heuristics
* Decoding the `returndata` of failed evm calls when possible

## Submodules

The submodules are these:
![image](https://github.com/NomicFoundation/edr/assets/176499/4d24dc43-6dfe-4cb2-9d39-716779a15e6e)

- Codebase model:An internal model of the codebase and compilation output that can be used to back all the runtime analysis that we need to do. This is found [here](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/hardhat-network/stack-traces/model.ts) in Hardhat. A 1:1 port would be Hard to express in Rust, and at the same time, there are multiple optimization opportunities. 
- build-info to codebase model: A module that given a build-info (i.e. compilation input & output pair), constructs the model described above.
- Contract identifier: A module that tries to identify which contract is being run in a certain evm call. Due to linked libraries, immutable variables inlining, and constructor parameters being appended to the bytecode, this is not a straightforward search. The most recent TS implementation of this is [here](https://github.com/NomicFoundation/hardhat/commit/618f44f4028f6f373c3944d951bf24b1302bbba4)
- EVM Trace Generation: A module that creates a static low-level trace of the execution of an EVM call. This has no knowledge of Solidity. It has already been implemented by @Wodann 
- Raw stack traces generation: A module that naively applies source maps to the EVM trace to generate a Solidity stack trace.
- Stack traces improver: A module that takes the naive solidity stack trace and improves them to be either more correct or meaningful. This is necessary due to the source maps generated by solidity being unreliable.
- Stack trace format: A format (i.e. data structure) that can be used to represent raw and improved stack traces. We can consider having two of them though. This can be ported 1:1 from Hardhat Network, as the format we used there has a mixture of responsibilities that we agreed was a mistake. It includes information about the `returndata` decoding result, and about any inferred error.
- Error inferred: A module that tries to detect common error cases in failed evm calls.
- Return data decoding: A module that tries to decode the `returndata` of a failed evm call. It should support revert reasons, custom errros and panics.
- EDR-to-JS format: We need to define a json format to return information about stack traces, decoded `returndata`s and any inferred error. It can potentially be returned by any JSON-RPC request that executes EVM code. Note that this may also affect how we handle the UI.
-  JS error construction: A javascript module that given the EDR-to-JS format explained above, creates a JavaScript `Error` object with the appropriate stack trace and information.

## Tasks

- [ ] Codebase model definition and construction
- [ ] Contract identifier implementation
- [ ] `returndata` decoding
- [ ] Stack trace format defintion
- [ ] Raw/naive stack trace generation
- [ ] Implement stack traces improver based on the heuristics that Hardhat Network has
- [ ] Port the Error inferred from Hardhat Network
- [ ] Define a JSON format to represent Solditiy stack traces, decoded `returndata` and inferred errors.
- [ ] Create js `Error`s that include Solidity stack traces, decoded `returnadta` and inferred errors information.
