### ISSUE TITLE
Achieve performance on par with EthereumJS mode on `main`

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#33]
When running Hardhat with EDR in third-party repos, runtimes of their test suites should be as fast or faster with EDR than EthereumJS (standard deviation of 5%).

- [x] Test in https://github.com/rocket-pool/rocketpool/ (EDR is 50% faster ✅ )
- [x] Test in https://github.com/safe-global/safe-contracts (EDR is 29% faster ✅ )
- [x] Test in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) (EDR is 10% faster ✅ )
- [x] Test in-process HH network in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) with logs enabled (EDR is 10% faster ✅ )
- [x] Test `ENABLE_GAS_REPORT=true npx hardhat test` in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) (EDR is 17% faster ✅ )
- [x] Test out of process HH network in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) (EDR is 25% faster ✅ )
- [x] Test `npx hardhat coverage` in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) (fails with latest released Hardhat and with EDR as well)
- [x] Test in https://github.com/Synthetixio/synthetix (EDR is 7% faster ✅ ; used HH 2.12 as baseline as tests fail with HH 2.20 and EDR@dbfd18e53)
- [x] Test in https://github.com/ProjectOpenSea/seaport/  (EDR is 5% faster ✅)
- [x] Test in https://github.com/Uniswap/v3-core  (EDR is 3.5% faster ✅)
- [x] Test in https://github.com/neptune-mutual-blue/protocol (EDR 20.9% slower ❌)
- [x] Test in https://github.com/NexusMutual/smart-contracts (can't run, see #254)
- [x] Test in https://github.com/smartcontractkit/chainlink/tree/develop/contracts (can't run, see #254)
- [x] Test in https://github.com/taikoxyz/taiko-mono (can't run, see #254)
- [x] Decide whether to test more based on https://www.notion.so/nomicfoundation/Testing-with-real-projects-bd896ef0b11c45fbb41eeb6df16e6584

This effort can be combined with validation testing in #254

**Comment by agostbiro** [comment]
The slowdown in [neptune-mutual-blue/protocol](https://github.com/neptune-mutual-blue/protocol) is due to expensive cloning of a large state when running `eth_estimateGas` in the `pending` block. With the current approach to state management this could be only avoided by introducing a lot of complexity. We've decided not to fix this for the `v0.2` release for two reasons:

1. We're planning to fundamentally change our state management for further performance improvements. The planned change will fix this problem as well without adding more complexity.
2. Hardhat tests don't call `eth_estimateGas` by default, so this is an edge case that shouldn't affect most users.
